### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by damianoazzolini** [friguzzi/auc#2]
When both `NPos` and `NNeg` in the `compute_pointsroc/8` call inside `compute_areas/5` are 0, a zero division error is raised.
A possible solution could be replacing 
```
compute_pointsroc(LG2,+1e20,0,0,NPos,NNeg,[],ROC) 
```
with 
```
  catch(compute_pointsroc(LG2,+1e20,0,0,NPos,NNeg,[],ROC), 
    error(evaluation_error(zero_divisor),_), 
    ROC = []
  )
```
Can this be a viable solution?

**Comment by friguzzi** [comment]
Sure. I have added you as a collaborator, I think you can push the change
